sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
before_install:               # install 阶段之前执行
  - npm install -g hexo-cli   # 全局安装 Hexo 命令行工具

install:                      # 在安装项目环境阶段需要运行的命令，一条一行，类似的还有 before_install
  - npm install               # 安装 package.json 中的依赖

script:                       # 在构建阶段需要运行的命令，一条一行，类似的还有 before_script、after_script
  - hexo clean
  - hexo generate             # Hexo 常规命令，执行清理和生成

branches:
  only:
    - gh-pages # build gh-pages branch only
target-branch: master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: gh-pages
  local-dir: public
